[package]
name = "crosshair_overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"
egui = "0.26.0"
winit = "0.29.0"
glow = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.13.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11.0" 